import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { sql, eq } from "drizzle-orm";
import { Hono } from "hono";

const scratch = await mkdtemp(join(tmpdir(), "publishing-regression-"));
process.env.DATABASE_URL = `pglite:${join(scratch, "db")}`;
process.env.UPLOAD_DIR = join(scratch, "assets");
process.env.ADMIN_API_KEY = randomBytes(32).toString("hex");
const { connectDatabase, closeDatabase } = await import("../db/client.js");
const { publishWorkers, publishJobs } = await import("../db/schema.js");
const service = await import("../services/publishing.js");
const { publishingAdminRoutes, publishingWorkerRoutes } = await import("../routes/publishing.js");
const { ApiError } = await import("../lib/http.js");
const db = await connectDatabase();
await db.execute(sql.raw("CREATE TABLE tenants (id serial PRIMARY KEY, slug text NOT NULL UNIQUE, name text NOT NULL, owner_token_hash text, active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now())"));
await db.execute(sql.raw("INSERT INTO tenants(slug,name) VALUES ('xmhua','Test'),('other','Other')"));
for (const statement of (await readFile(new URL("../../drizzle/0008_video_publishing.sql", import.meta.url), "utf8")).split("--> statement-breakpoint")) await db.execute(sql.raw(statement));
const app = new Hono();
app.route("/api/admin/publishing", publishingAdminRoutes);
app.route("/api/publishing-worker", publishingWorkerRoutes);
app.onError((e, c) => e instanceof ApiError ? c.json({ error: e.code }, e.status as 400) : c.json({ error: "unexpected" }, 500));
const admin = { authorization: `Bearer ${process.env.ADMIN_API_KEY}`, "content-type": "application/json" };
assert.equal((await app.request("/api/admin/publishing")).status, 401);
assert.equal((await app.request("/api/publishing-worker/claim", { method: "POST" })).status, 401);
const worker = await service.createWorker(1, "Test PC");
const other = await service.createWorker(2, "Other PC");
const wh = { authorization: `Bearer ${worker.token}`, "content-type": "application/json" };
await db.update(publishWorkers).set({ lastSeen: new Date() }).where(eq(publishWorkers.id, worker.id));
const input = service.jobInput.parse({ requestId: randomUUID(), workerId: worker.id, kind: "check", platforms: ["douyin", "youtube"] });
await service.enqueue(1, input); await service.enqueue(1, input);
assert.equal((await service.overview(1)).jobs.length, 2, "idempotent multi-platform submission");
await Promise.all(["login", "check"].map(kind => service.enqueue(1, { ...input, requestId: randomUUID(), kind: kind as "login" | "check" })));
assert.equal((await service.overview(1)).jobs.length, 2, "different requests/tabs cannot duplicate pending account tasks");
assert.equal((await service.overview(2)).jobs.length, 0, "tenant isolation");
assert.ok(!JSON.stringify(await service.overview(1)).includes(worker.token), "never expose credentials");
await assert.rejects(service.enqueue(2, input), /WORKER_NOT_FOUND/);
const first = await service.claim(worker.id);
assert.ok(first);
assert.equal(await service.claim(worker.id), null, "no second action while running");
await service.enqueue(1, { ...input, requestId: randomUUID(), kind: "login" });
assert.equal((await service.overview(1)).jobs.length, 2, "running login/check also blocks duplicate account work");
await assert.rejects(service.report(other.id, first.id, { state: "completed", message: "" }), /JOB_NOT_RUNNING/);
await service.report(worker.id, first.id, { state: "completed", message: "checked", authenticated: false });
await assert.rejects(service.report(worker.id, first.id, { state: "completed", message: "" }), /JOB_NOT_RUNNING/);
const second = await service.claim(worker.id); assert.ok(second);
assert.equal((await app.request("/api/publishing-worker/recover", { method: "POST", headers: { authorization: `Bearer ${other.token}` } })).status, 200);
assert.equal((await service.overview(1)).jobs.find(job => job.id === second.id)?.state, "running", "recovery cannot change another worker's job");
assert.equal((await app.request("/api/publishing-worker/recover", { method: "POST", headers: wh })).status, 200);
assert.equal((await service.overview(1)).jobs.find(job => job.id === second.id)?.state, "needs_attention");
assert.equal(await service.claim(worker.id), null, "uncertain jobs never replay");
assert.equal((await app.request("/api/admin/publishing/jobs", { method: "POST", headers: { ...admin, origin: "https://attacker.invalid" }, body: JSON.stringify(input) })).status, 403);
assert.equal((await app.request("/api/admin/publishing/assets", { method: "POST", headers: admin, body: "not an mp4" })).status, 400);
assert.equal((await app.request("/api/admin/publishing/assets", { method: "POST", headers: { ...admin, "content-length": String(600 * 1024 * 1024) }, body: "x" })).status, 413);
const video = Buffer.from([0,0,0,24,102,116,121,112,109,112,52,50,0,0,0,0]);
const uploaded = await app.request("/api/admin/publishing/assets", { method: "POST", headers: { ...admin, "x-file-name": "test.mp4" }, body: video });
assert.equal(uploaded.status, 201);
const asset = ((await uploaded.json()) as { data: { id: string } }).data;
assert.equal((await app.request(`/api/publishing-worker/assets/${asset.id}`, { headers: { authorization: `Bearer ${other.token}` } })).status, 404);
assert.equal((await app.request(`/api/publishing-worker/assets/${asset.id}`, { headers: wh })).status, 200);
await assert.rejects(service.enqueue(1, { ...input, kind: "publish", assetId: asset.id, title: "Test" }), /ACCOUNT_CHECK_REQUIRED/);
await db.update(publishWorkers).set({ active: false }).where(eq(publishWorkers.id, worker.id));
await assert.rejects(service.authenticateWorker(worker.token), /UNAUTHORIZED/);
assert.equal((await db.select().from(publishJobs)).length, 2);
await closeDatabase();
console.log("PASS: auth, tenant isolation, streamed upload validation, idempotency, claim serialization, receipt ownership, revocation and no automatic replay");
